version: '3.9'

services:
  bank-transactions-app:
    build: .
    container_name: bank-transactions-app
    restart: always
    env_file:
      - .env
    environment:
      - ENV=local
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - HTTP_HOST=localhost
      - HTTP_PORT=8080
      - WAIT_HOSTS=posgresdb:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - postgres
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    networks:
      - application

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - application

networks:
  application:
    driver: bridge
